//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erzasoft.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Erzasoft.Service.Resources.ModelResource", typeof(ModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string AllocationName {
            get {
                return ResourceManager.GetString("AllocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte název..
        /// </summary>
        public static string AllocationNameRequired {
            get {
                return ResourceManager.GetString("AllocationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barva.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte barvu..
        /// </summary>
        public static string ColorRequired {
            get {
                return ResourceManager.GetString("ColorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        public static string Ean {
            get {
                return ResourceManager.GetString("Ean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyřazen.
        /// </summary>
        public static string IsDisabled {
            get {
                return ResourceManager.GetString("IsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je vidět.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charakteristika.
        /// </summary>
        public static string ProductCharacter {
            get {
                return ResourceManager.GetString("ProductCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleva.
        /// </summary>
        public static string ProductCut {
            get {
                return ResourceManager.GetString("ProductCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte slevu..
        /// </summary>
        public static string ProductCutRequired {
            get {
                return ResourceManager.GetString("ProductCutRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte popisek..
        /// </summary>
        public static string ProductDescriptionRequired {
            get {
                return ResourceManager.GetString("ProductDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krátký popis.
        /// </summary>
        public static string ProductDescriptionShort {
            get {
                return ResourceManager.GetString("ProductDescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte krátký popis..
        /// </summary>
        public static string ProductDescriptionShortRequired {
            get {
                return ResourceManager.GetString("ProductDescriptionShortRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrázek.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte obrázek..
        /// </summary>
        public static string ProductImageRequired {
            get {
                return ResourceManager.GetString("ProductImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis obrázku.
        /// </summary>
        public static string ProductImageTitle {
            get {
                return ResourceManager.GetString("ProductImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte popis obrázku..
        /// </summary>
        public static string ProductImageTitleRequired {
            get {
                return ResourceManager.GetString("ProductImageTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V akci.
        /// </summary>
        public static string ProductInAction {
            get {
                return ResourceManager.GetString("ProductInAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V sortimentu.
        /// </summary>
        public static string ProductInSortiment {
            get {
                return ResourceManager.GetString("ProductInSortiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte název produktu..
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Původní cena.
        /// </summary>
        public static string ProductOriginalPrice {
            get {
                return ResourceManager.GetString("ProductOriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte původní cenu s daní..
        /// </summary>
        public static string ProductOriginalPriceRequired {
            get {
                return ResourceManager.GetString("ProductOriginalPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmakoterapeutická skupina.
        /// </summary>
        public static string ProductPharmGroup {
            get {
                return ResourceManager.GetString("ProductPharmGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte cenu..
        /// </summary>
        public static string ProductPriceRequired {
            get {
                return ResourceManager.GetString("ProductPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množství.
        /// </summary>
        public static string ProductQuantity {
            get {
                return ResourceManager.GetString("ProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte množství..
        /// </summary>
        public static string ProductQuantityRequired {
            get {
                return ResourceManager.GetString("ProductQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připraveno.
        /// </summary>
        public static string ProductReady {
            get {
                return ResourceManager.GetString("ProductReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO popisek.
        /// </summary>
        public static string ProductSeoDataDescription {
            get {
                return ResourceManager.GetString("ProductSeoDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO Klíčová slova.
        /// </summary>
        public static string ProductSeoDataKeywords {
            get {
                return ResourceManager.GetString("ProductSeoDataKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO název.
        /// </summary>
        public static string ProductSeoDataTitle {
            get {
                return ResourceManager.GetString("ProductSeoDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO url.
        /// </summary>
        public static string ProductShortUrlId {
            get {
                return ResourceManager.GetString("ProductShortUrlId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladem.
        /// </summary>
        public static string ProductStock {
            get {
                return ResourceManager.GetString("ProductStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOLF doplněk.
        /// </summary>
        public static string ProductSupplement {
            get {
                return ResourceManager.GetString("ProductSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte doplněk..
        /// </summary>
        public static string ProductSupplementRequired {
            get {
                return ResourceManager.GetString("ProductSupplementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daň.
        /// </summary>
        public static string ProductTax {
            get {
                return ResourceManager.GetString("ProductTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte daň..
        /// </summary>
        public static string ProductTaxRequired {
            get {
                return ResourceManager.GetString("ProductTaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daň.
        /// </summary>
        public static string ProductVat {
            get {
                return ResourceManager.GetString("ProductVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte daň..
        /// </summary>
        public static string ProductVatRequired {
            get {
                return ResourceManager.GetString("ProductVatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váha.
        /// </summary>
        public static string ProductWeight {
            get {
                return ResourceManager.GetString("ProductWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, vyplňte váhu..
        /// </summary>
        public static string ProductWeightRequired {
            get {
                return ResourceManager.GetString("ProductWeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO popis.
        /// </summary>
        public static string SeoDataDescription {
            get {
                return ResourceManager.GetString("SeoDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO klíčová slova.
        /// </summary>
        public static string SeoDataKeywords {
            get {
                return ResourceManager.GetString("SeoDataKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO název.
        /// </summary>
        public static string SeoDataTitle {
            get {
                return ResourceManager.GetString("SeoDataTitle", resourceCulture);
            }
        }
    }
}
